### ISSUE TITLE
Crytpminisat version with approxmc3? 

### ISSUE THREAD

**Issue by deepali9** [meelgroup/mis#6]
Which version of cryptominisat is compatible with approxmc 3?

**Comment by msoos** [comment]
Hi,

This is a really good question, thanks so much for asking ! I have now updated the release of ApproxMC3 to explain this in detail:

https://github.com/meelgroup/approxmc/releases/tag/3.0

Please make **sure** you use [that specific version of CryptoMiniSat](https://github.com/msoos/cryptominisat/tree/bccc0c2de8981fceab6726db89c1a00e84493783) together with ApproxMC3. Or, alternatively, use the precompiled Linux binary that's attached to that release.  Otherwise, you may use parts of ApproxMC4, because a large part of ApproxMC4 was implemented into CryptoMiniSat.

By the way, please next time file such requests under CryptoMiniSat, as this request belongs there :)

Cheers and thanks again for asking, this was a great question to improve our documentation!
